### PR TITLE
ENH added pizza-cutter input generation

### PR DESCRIPTION
**Pull request by beckermr**
This PR adds code to generate the YAML files for the pizza cutter. Here is how you do it

```
query_coadd_for_meds.py -A 2758897 -o test_run/junk --segmap --bkgimg --psfmodel --usepiff --imglist test_run/test.img.list --ima_list test_run/test.ima.list --head_list test_run/test.head.list --bkg_list test_run/test.bkg.list --seg_list test_run/test.seg.list --psf_list test_run/test.psf.list -s db-desoper -S prod -v 2 --pifftag Y6A1_PIFF --zeropoint NONE --pizza-cutter-yaml=test_run/pizza --me_proctag=Y6A2_COADD
```

This call produces files like `test_run/pizza_r.yaml` etc for the bands riz.

### CODE REVIEW

**Comment by beckermr** [comment]
cc @menanteau @rgruendl @esheldon

**Review by rgruendl — COMMENTED** [review]
So the question I see is that has to make assumptions about where the other files will lie (and what they will be named) based on the coadd images.   Better would be to actually query for them... I can help with that...  but in the meantime, if we simply want to try this... I think it should work.

**Comment by beckermr** [comment]
Right. We should do it right. Happy to change it if I have the correct query.

**Comment by beckermr** [comment]
OK @rgruendl 

I added query code for the other file data for the coadds. The outputs appear correct locally. 

Ready for another look!

**Comment by menanteau** [comment]
@beckermr could you replace the `pyyaml` prereq to:
`setupRequired(pyyaml 5.3+0)` on the `ups/MEPipelineAppIntg.table` file.

**Comment by beckermr** [comment]
OK @menanteau I added the correct pyyaml versions and fixed the missing tilename key.

**Comment by menanteau** [comment]
Looks good. Merging.

**Pull request merged**
